hello

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
arr= np.array([0.1,0.4,0.6,0.8,1.1,1.2,1.3,1.5,1.9,2.1,2.2,2.8,3.2])

In [ ]:
print("Max:", np.max(arr))

Max: 3.2

In [ ]:
print("Min:", np.min(arr))

Min: 0.1

In [ ]:
print("Median:", np.median(arr))

Median: 1.3

In [ ]:
print("Mean:", np.mean(arr))

Mean: 1.4769230769230768

In [ ]:
print("Variance:", np.var(arr))

Variance: 0.7956213017751478

In [ ]:
print("Standard Deviation:", np.std(arr))

Standard Deviation: 0.8919760656963548

In [ ]:
arr.shape

(13,)

In [ ]:
Data = pd.read_csv('/content/drive/MyDrive/IGSLab_ML course/preprocessing/heart.csv')
#Data = pd.read_csv(r'/content/drive/MyDrive/IGSLab_ML course/preprocessing/heart.csv'), r bezarim ke slash ha ro dorost be shekle path bekhune tu systeme local

In [ ]:
Data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52.0,male,0.0,125.0,212.0,False,1.0,168.0,0.0,1.0,2.0,2.0,3.0,0.0
1,53.0,male,0.0,140.0,203.0,True,0.0,155.0,1.0,3.1,0.0,0.0,3.0,0.0
2,70.0,male,0.0,145.0,174.0,False,1.0,125.0,1.0,2.6,0.0,0.0,3.0,0.0
3,61.0,male,0.0,148.0,203.0,False,1.0,161.0,0.0,0.0,2.0,1.0,3.0,0.0
4,62.0,female,0.0,138.0,294.0,True,1.0,106.0,0.0,1.9,1.0,3.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59.0,male,1.0,140.0,221.0,False,1.0,164.0,1.0,0.0,2.0,0.0,2.0,1.0
1021,60.0,male,0.0,125.0,258.0,False,0.0,141.0,1.0,2.8,1.0,1.0,3.0,0.0
1022,47.0,male,0.0,110.0,275.0,False,0.0,118.0,1.0,1.0,1.0,1.0,2.0,0.0
1023,50.0,female,0.0,110.0,254.0,False,0.0,159.0,0.0,0.0,2.0,0.0,2.0,1.0
1024,54.0,male,0.0,120.0,188.0,False,1.0,113.0,0.0,1.4,1.0,1.0,3.0,0.0

In [ ]:
print(Data.shape)

(1025, 14)

In [ ]:
#check for missing values
Data.isnull()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1021,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1022,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1023,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1024,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
Data.isnull().sum()

age         7
sex         0
cp          2
trestbps    8
chol        6
fbs         0
restecg     1
thalach     6
exang       4
oldpeak     5
slope       2
ca          8
thal        3
target      1
dtype: int64

In [ ]:
Data.isnull().sum().sum()

53

In [ ]:
dataset_new= Data.dropna()
print(dataset_new.shape)
dataset_new

(984, 14)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52.0,male,0.0,125.0,212.0,False,1.0,168.0,0.0,1.0,2.0,2.0,3.0,0.0
1,53.0,male,0.0,140.0,203.0,True,0.0,155.0,1.0,3.1,0.0,0.0,3.0,0.0
2,70.0,male,0.0,145.0,174.0,False,1.0,125.0,1.0,2.6,0.0,0.0,3.0,0.0
3,61.0,male,0.0,148.0,203.0,False,1.0,161.0,0.0,0.0,2.0,1.0,3.0,0.0
4,62.0,female,0.0,138.0,294.0,True,1.0,106.0,0.0,1.9,1.0,3.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59.0,male,1.0,140.0,221.0,False,1.0,164.0,1.0,0.0,2.0,0.0,2.0,1.0
1021,60.0,male,0.0,125.0,258.0,False,0.0,141.0,1.0,2.8,1.0,1.0,3.0,0.0
1022,47.0,male,0.0,110.0,275.0,False,0.0,118.0,1.0,1.0,1.0,1.0,2.0,0.0
1023,50.0,female,0.0,110.0,254.0,False,0.0,159.0,0.0,0.0,2.0,0.0,2.0,1.0
1024,54.0,male,0.0,120.0,188.0,False,1.0,113.0,0.0,1.4,1.0,1.0,3.0,0.0

In [ ]:
#filling null values with a single value(matn ya adad)
new_dataset = Data.fillna(0)
new_dataset

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52.0,male,0.0,125.0,212.0,False,1.0,168.0,0.0,1.0,2.0,2.0,3.0,0.0
1,53.0,male,0.0,140.0,203.0,True,0.0,155.0,1.0,3.1,0.0,0.0,3.0,0.0
2,70.0,male,0.0,145.0,174.0,False,1.0,125.0,1.0,2.6,0.0,0.0,3.0,0.0
3,61.0,male,0.0,148.0,203.0,False,1.0,161.0,0.0,0.0,2.0,1.0,3.0,0.0
4,62.0,female,0.0,138.0,294.0,True,1.0,106.0,0.0,1.9,1.0,3.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59.0,male,1.0,140.0,221.0,False,1.0,164.0,1.0,0.0,2.0,0.0,2.0,1.0
1021,60.0,male,0.0,125.0,258.0,False,0.0,141.0,1.0,2.8,1.0,1.0,3.0,0.0
1022,47.0,male,0.0,110.0,275.0,False,0.0,118.0,1.0,1.0,1.0,1.0,2.0,0.0
1023,50.0,female,0.0,110.0,254.0,False,0.0,159.0,0.0,0.0,2.0,0.0,2.0,1.0
1024,54.0,male,0.0,120.0,188.0,False,1.0,113.0,0.0,1.4,1.0,1.0,3.0,0.0

In [ ]:
#filling null values with previous values(moshkelesh radife avale)

new= Data.fillna(method= 'pad')
new

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52.0,male,0.0,125.0,212.0,False,1.0,168.0,0.0,1.0,2.0,2.0,3.0,0.0
1,53.0,male,0.0,140.0,203.0,True,0.0,155.0,1.0,3.1,0.0,0.0,3.0,0.0
2,70.0,male,0.0,145.0,174.0,False,1.0,125.0,1.0,2.6,0.0,0.0,3.0,0.0
3,61.0,male,0.0,148.0,203.0,False,1.0,161.0,0.0,0.0,2.0,1.0,3.0,0.0
4,62.0,female,0.0,138.0,294.0,True,1.0,106.0,0.0,1.9,1.0,3.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59.0,male,1.0,140.0,221.0,False,1.0,164.0,1.0,0.0,2.0,0.0,2.0,1.0
1021,60.0,male,0.0,125.0,258.0,False,0.0,141.0,1.0,2.8,1.0,1.0,3.0,0.0
1022,47.0,male,0.0,110.0,275.0,False,0.0,118.0,1.0,1.0,1.0,1.0,2.0,0.0
1023,50.0,female,0.0,110.0,254.0,False,0.0,159.0,0.0,0.0,2.0,0.0,2.0,1.0
1024,54.0,male,0.0,120.0,188.0,False,1.0,113.0,0.0,1.4,1.0,1.0,3.0,0.0

In [ ]:
#filling null values with next values(moshkelesh radife akhare)

new= Data.fillna(method= 'bfill')
new

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52.0,male,0.0,125.0,212.0,False,1.0,168.0,0.0,1.0,2.0,2.0,3.0,0.0
1,53.0,male,0.0,140.0,203.0,True,0.0,155.0,1.0,3.1,0.0,0.0,3.0,0.0
2,70.0,male,0.0,145.0,174.0,False,1.0,125.0,1.0,2.6,0.0,0.0,3.0,0.0
3,61.0,male,0.0,148.0,203.0,False,1.0,161.0,0.0,0.0,2.0,1.0,3.0,0.0
4,62.0,female,0.0,138.0,294.0,True,1.0,106.0,0.0,1.9,1.0,3.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59.0,male,1.0,140.0,221.0,False,1.0,164.0,1.0,0.0,2.0,0.0,2.0,1.0
1021,60.0,male,0.0,125.0,258.0,False,0.0,141.0,1.0,2.8,1.0,1.0,3.0,0.0
1022,47.0,male,0.0,110.0,275.0,False,0.0,118.0,1.0,1.0,1.0,1.0,2.0,0.0
1023,50.0,female,0.0,110.0,254.0,False,0.0,159.0,0.0,0.0,2.0,0.0,2.0,1.0
1024,54.0,male,0.0,120.0,188.0,False,1.0,113.0,0.0,1.4,1.0,1.0,3.0,0.0

In [ ]:
#filling null value with the median(baraye har sotun hesab mikone)
new= Data.copy()
missing_columns = new.isnull().any()
for column in missing_columns[missing_columns].index:
  new[column].fillna(new[column].median(), inplace=True)
new

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52.0,male,0.0,125.0,212.0,False,1.0,168.0,0.0,1.0,2.0,2.0,3.0,0.0
1,53.0,male,0.0,140.0,203.0,True,0.0,155.0,1.0,3.1,0.0,0.0,3.0,0.0
2,70.0,male,0.0,145.0,174.0,False,1.0,125.0,1.0,2.6,0.0,0.0,3.0,0.0
3,61.0,male,0.0,148.0,203.0,False,1.0,161.0,0.0,0.0,2.0,1.0,3.0,0.0
4,62.0,female,0.0,138.0,294.0,True,1.0,106.0,0.0,1.9,1.0,3.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59.0,male,1.0,140.0,221.0,False,1.0,164.0,1.0,0.0,2.0,0.0,2.0,1.0
1021,60.0,male,0.0,125.0,258.0,False,0.0,141.0,1.0,2.8,1.0,1.0,3.0,0.0
1022,47.0,male,0.0,110.0,275.0,False,0.0,118.0,1.0,1.0,1.0,1.0,2.0,0.0
1023,50.0,female,0.0,110.0,254.0,False,0.0,159.0,0.0,0.0,2.0,0.0,2.0,1.0
1024,54.0,male,0.0,120.0,188.0,False,1.0,113.0,0.0,1.4,1.0,1.0,3.0,0.0

In [ ]:
new= Data.copy()
missing_columns = new.isnull().any()
for column in missing_columns[missing_columns].index:
  new[column].fillna(new[column].mode()[0], inplace=True) #0 ro mizrim ke bege avalin por tekrari ke peida mikoni ro bezar
new

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52.0,male,0.0,125.0,212.0,False,1.0,168.0,0.0,1.0,2.0,2.0,3.0,0.0
1,53.0,male,0.0,140.0,203.0,True,0.0,155.0,1.0,3.1,0.0,0.0,3.0,0.0
2,70.0,male,0.0,145.0,174.0,False,1.0,125.0,1.0,2.6,0.0,0.0,3.0,0.0
3,61.0,male,0.0,148.0,203.0,False,1.0,161.0,0.0,0.0,2.0,1.0,3.0,0.0
4,62.0,female,0.0,138.0,294.0,True,1.0,106.0,0.0,1.9,1.0,3.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59.0,male,1.0,140.0,221.0,False,1.0,164.0,1.0,0.0,2.0,0.0,2.0,1.0
1021,60.0,male,0.0,125.0,258.0,False,0.0,141.0,1.0,2.8,1.0,1.0,3.0,0.0
1022,47.0,male,0.0,110.0,275.0,False,0.0,118.0,1.0,1.0,1.0,1.0,2.0,0.0
1023,50.0,female,0.0,110.0,254.0,False,0.0,159.0,0.0,0.0,2.0,0.0,2.0,1.0
1024,54.0,male,0.0,120.0,188.0,False,1.0,113.0,0.0,1.4,1.0,1.0,3.0,0.0

In [ ]:
new= Data.copy()
missing_columns = new.isnull().any()
for column in missing_columns[missing_columns].index:
  new[column].fillna(new[column].mean(), inplace=True)
new

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52.0,male,0.0,125.0,212.0,False,1.0,168.0,0.0,1.0,2.0,2.0,3.0,0.0
1,53.0,male,0.0,140.0,203.0,True,0.0,155.0,1.0,3.1,0.0,0.0,3.0,0.0
2,70.0,male,0.0,145.0,174.0,False,1.0,125.0,1.0,2.6,0.0,0.0,3.0,0.0
3,61.0,male,0.0,148.0,203.0,False,1.0,161.0,0.0,0.0,2.0,1.0,3.0,0.0
4,62.0,female,0.0,138.0,294.0,True,1.0,106.0,0.0,1.9,1.0,3.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59.0,male,1.0,140.0,221.0,False,1.0,164.0,1.0,0.0,2.0,0.0,2.0,1.0
1021,60.0,male,0.0,125.0,258.0,False,0.0,141.0,1.0,2.8,1.0,1.0,3.0,0.0
1022,47.0,male,0.0,110.0,275.0,False,0.0,118.0,1.0,1.0,1.0,1.0,2.0,0.0
1023,50.0,female,0.0,110.0,254.0,False,0.0,159.0,0.0,0.0,2.0,0.0,2.0,1.0
1024,54.0,male,0.0,120.0,188.0,False,1.0,113.0,0.0,1.4,1.0,1.0,3.0,0.0

In [ ]:
#kod haye ziadi goft baraye tabdile dadehaye peyvaste be gosaste masalan vazn be 5 ta daste 0 ta 4

In [ ]:

sex_mapping= {'male':0, 'female':1}
fbs_mapping= {'True':1, 'False':0}
Data['sex']= Data['sex'].map(sex_mapping)
Data['fbs']= Data['fbs'].map(fbs_mapping)

In [ ]:
Data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52.0,NaN,0.0,125.0,212.0,NaN,1.0,168.0,0.0,1.0,2.0,2.0,3.0,0.0
1,53.0,NaN,0.0,140.0,203.0,NaN,0.0,155.0,1.0,3.1,0.0,0.0,3.0,0.0
2,70.0,NaN,0.0,145.0,174.0,NaN,1.0,125.0,1.0,2.6,0.0,0.0,3.0,0.0
3,61.0,NaN,0.0,148.0,203.0,NaN,1.0,161.0,0.0,0.0,2.0,1.0,3.0,0.0
4,62.0,NaN,0.0,138.0,294.0,NaN,1.0,106.0,0.0,1.9,1.0,3.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59.0,NaN,1.0,140.0,221.0,NaN,1.0,164.0,1.0,0.0,2.0,0.0,2.0,1.0
1021,60.0,NaN,0.0,125.0,258.0,NaN,0.0,141.0,1.0,2.8,1.0,1.0,3.0,0.0
1022,47.0,NaN,0.0,110.0,275.0,NaN,0.0,118.0,1.0,1.0,1.0,1.0,2.0,0.0
1023,50.0,NaN,0.0,110.0,254.0,NaN,0.0,159.0,0.0,0.0,2.0,0.0,2.0,1.0
1024,54.0,NaN,0.0,120.0,188.0,NaN,1.0,113.0,0.0,1.4,1.0,1.0,3.0,0.0

In [ ]:
#true va false vase khode system be onvane 0 , 1 tarif shode vase hamin dobare nemikhune

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/IGSLab_ML course/ML/diabetes.csv')
scaler= MinMaxScaler()
normalized_glucose= scaler.fit_transform(data[['Glucose']])
data['Glucose']= normalized_glucose
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,0.743719,72,35,0,33.6,0.627,50,1
1,1,0.427136,66,29,0,26.6,0.351,31,0
2,8,0.919598,64,0,0,23.3,0.672,32,1
3,1,0.447236,66,23,94,28.1,0.167,21,0
4,0,0.688442,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,0.507538,76,48,180,32.9,0.171,63,0
764,2,0.613065,70,27,0,36.8,0.340,27,0
765,5,0.608040,72,23,112,26.2,0.245,30,0
766,1,0.633166,60,0,0,30.1,0.349,47,1
767,1,0.467337,70,31,0,30.4,0.315,23,0

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
normalized_glucose= scaler.fit_transform(data[['Glucose']])
data['Glucose']= normalized_glucose
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,0.848324,72,35,0,33.6,0.627,50,1
1,1,-1.123396,66,29,0,26.6,0.351,31,0
2,8,1.943724,64,0,0,23.3,0.672,32,1
3,1,-0.998208,66,23,94,28.1,0.167,21,0
4,0,0.504055,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,-0.622642,76,48,180,32.9,0.171,63,0
764,2,0.034598,70,27,0,36.8,0.340,27,0
765,5,0.003301,72,23,112,26.2,0.245,30,0
766,1,0.159787,60,0,0,30.1,0.349,47,1
767,1,-0.873019,70,31,0,30.4,0.315,23,0

In [ ]:
print(np.mean(data['Glucose']))
print(np.std(data['Glucose']))

2.706168622523819e-16
0.9999999999999998

In [ ]:
#miangin ro taghriban sefr karde std ro taghriban yek

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x = data.iloc[:,:-1] #all columns except the last one
y = data.iloc[:, -1] #last column(target)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=168, train_size= 600, random_state=42)
#haminjuri 42 yani ya adad mizari ya nan

In [ ]:
print('x_train shape:', x_train.shape)
print('y_train shape:', y_train.shape)
print('x_test shape:', x_test.shape)
print('y_test shape:', y_test.shape)

x_train shape: (600, 8)
y_train shape: (600,)
x_test shape: (168, 8)
y_test shape: (168,)

In [ ]:
x

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,0.848324,72,35,0,33.6,0.627,50
1,1,-1.123396,66,29,0,26.6,0.351,31
2,8,1.943724,64,0,0,23.3,0.672,32
3,1,-0.998208,66,23,94,28.1,0.167,21
4,0,0.504055,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,-0.622642,76,48,180,32.9,0.171,63
764,2,0.034598,70,27,0,36.8,0.340,27
765,5,0.003301,72,23,112,26.2,0.245,30
766,1,0.159787,60,0,0,30.1,0.349,47
767,1,-0.873019,70,31,0,30.4,0.315,23

In [ ]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [ ]:
x_train

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
260,3,2.194101,68,15,130,30.9,0.299,34
131,9,0.034598,56,0,0,33.3,1.114,33
44,7,1.192592,64,0,0,27.4,0.294,40
70,2,-0.653939,66,20,90,32.9,0.867,28
264,4,0.065895,62,0,0,32.0,0.226,35
...,...,...,...,...,...,...,...,...
71,5,0.566649,64,35,140,28.6,0.411,26
106,1,-0.779128,122,0,0,22.4,0.207,27
270,10,-0.622642,86,37,0,45.6,1.136,38
435,0,0.629244,0,0,0,42.4,0.205,29
102,0,0.128489,96,0,0,22.5,0.262,21

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print('Train:')
print('x_train shape:', x_train.shape)
print('y_train shape:', y_train.shape)
print('Test:')
print('x_test shape:', x_test.shape)
print('y_test shape:', y_test.shape)

Train:
x_train shape: (614, 8)
y_train shape: (614,)
Test:
x_test shape: (154, 8)
y_test shape: (154,)

In [ ]:
x

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,0.848324,72,35,0,33.6,0.627,50
1,1,-1.123396,66,29,0,26.6,0.351,31
2,8,1.943724,64,0,0,23.3,0.672,32
3,1,-0.998208,66,23,94,28.1,0.167,21
4,0,0.504055,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,-0.622642,76,48,180,32.9,0.171,63
764,2,0.034598,70,27,0,36.8,0.340,27
765,5,0.003301,72,23,112,26.2,0.245,30
766,1,0.159787,60,0,0,30.1,0.349,47
767,1,-0.873019,70,31,0,30.4,0.315,23

In [ ]:
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectKBest

In [ ]:
chi2_selector=SelectKBest(chi2, k=2)
x_kbest= chi2_selector.fit_transform(x,y)
print(x_kbest)

[[  0.  50.]
 [  0.  31.]
 [  0.  32.]
 ...
 [112.  30.]
 [  0.  47.]
 [  0.  23.]]

In [ ]:
selected_feature_indices= chi2_selector.get_support(indices=True)
feature_names= x.columns.tolist()
selected_feature_names= [feature_names[i] for i in selected_feature_indices]
print('selected feature names:', selected_feature_names)

selected feature names: ['Insulin', 'Age']

In [ ]:
#javab motafavet ba ostad darim chon faghat yeki az sotun ha normal shode